# Generated by Django 3.1 on 2020-09-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtuser',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='邮箱'),
        ),
    ]
