# Generated by Django 3.1 on 2020-09-05 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商家名称')),
                ('address', models.CharField(max_length=200, verbose_name='商家地址')),
                ('logo', models.URLField(verbose_name='商家logo')),
                ('notice', models.CharField(blank=True, max_length=200, verbose_name='商家公告')),
                ('up_send', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='起送价')),
                ('lon', models.FloatField(verbose_name='经度')),
                ('lat', models.FloatField(verbose_name='纬度')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='品名分类')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='meituan.merchant', verbose_name='所属商家')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('picture', models.URLField(verbose_name='商品图片')),
                ('intro', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='商品价格')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_list', to='meituan.goodscategory', verbose_name='所属分类')),
            ],
        ),
    ]
